### ISSUE TITLE
Not compatible with auth0-java version 1.0.0

### ISSUE THREAD

**Issue by mostekcm** [auth0/auth0-servlet#51]
In the 1.0.0 version they moved the exception class to com.auth0.exception.Auth0Exception.  This breaks in the Auth0Filter.java class (and maybe others too).

**Comment by rmoquin** [comment]
I was actually really confused about this.  Apparently the latest version of this library can't work with the latest version of mvc-auth-commons or auth0-java since a bunch of classes were removed  from the 0.1.2 version of mvc-auth0-commons.  I was trying to use mvc-auth-commons 1.0.0 and the latest auth0-java but kept have problems with missing classes until I finally noticed that these classes are no longer in the newest mvc-auth-commons.  Is this library no longer supposed to be used or will be updated?  The mvc-auth-commons that is compatible is based off a git branch that isn't compatible with the master branch so I'm very confused.
I was basing things off the auth0 servlet examples, but then noticed there is some prebuilt filters and servlets that can be leveraged which do a lot more., but then you can't use the latest of the auth0 java library... I guess at this point, I'll revert back to building functionality into the servlet and filters in the example so I can use the latest auth0 libraries and I guess stop using this library since it isn't compatible with the newest stuff :(  I think I'm partially confused since it says the common library is used across the other mvc libraries, but the latest code isn't.....

**Comment by rmoquin** [comment]
Actually, as usually happens,  after I post something, I magically stumble on what is probably the answer, it looks like this library is going to no longer maintained as a project, since this is stated in the example branch.  I think the master branch should also be updated to say this as it would have alleviated the last couple hours of trying to switch to using the build in auth0-servlet with the newer mvc commons and auth0 java libraries ..... :)  Oh well.  Hopefully this helps mostekcm

**Comment by lbalmaceda** [comment]
Probably this library will no longer be maintained. As you mentioned, there is an `example` branch that uses the latest [mvc-commons](https://github.com/auth0/auth0-java-mvc-common) library. That is the first major release of the library and of course, the API has changed: Our idea is to have a single library to handle all possible MVC authentication scenarios, so the filter implementation is now a responsibility of the user, as independent as possible from any framework. 
Eventually, we will swap the master and example branches. I will add the warning on the readme.
